apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: helper
  labels:
    app: helper
  namespace: istio-course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helper
  template:
    metadata:
      labels:
        app: helper
    spec:
      containers:
      - name: nginx
        image: nginx:alpine